# Generated by Django 4.2.3 on 2023-08-21 10:09

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('emailId', models.EmailField(blank=True, max_length=255, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('otpChecked', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisorId', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='familyHeadDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyId', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('firstName', models.CharField(blank=True, max_length=500, null=True)),
                ('middelName', models.CharField(blank=True, max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('mobileNo', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('plotNo', models.CharField(blank=True, max_length=50, null=True)),
                ('addressLine1', models.CharField(blank=True, max_length=500, null=True)),
                ('addressLine2', models.CharField(blank=True, max_length=500, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('totalFamilyMembers', models.IntegerField(default=0)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('partialSubmit', models.BooleanField(default=False)),
                ('wardName', models.CharField(blank=True, max_length=100, null=True)),
                ('healthPost', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveyDoneBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sendOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otpVerified', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('expireyDate', models.DateTimeField(blank=True, null=True)),
                ('registerUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Registeruser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientsPathlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestAssignedAndReport', models.JSONField(blank=True, null=True)),
                ('doctorRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('PathLabRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('PathLab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PathLab', to=settings.AUTH_USER_MODEL)),
                ('ReportCheckByDoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReportCheckByDoctor', to=settings.AUTH_USER_MODEL)),
                ('pathLabPatient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathLabPatient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='familyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=900, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('aadharCard', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('abhaId', models.CharField(blank=True, max_length=100, unique=True)),
                ('partA', models.JSONField(blank=True, null=True)),
                ('partB', models.JSONField(blank=True, null=True)),
                ('partC', models.JSONField(blank=True, null=True)),
                ('partD', models.JSONField(blank=True, null=True)),
                ('partE', models.JSONField(blank=True, null=True)),
                ('bloodCollectionLocation', models.CharField(blank=True, choices=[('Home', 'Home'), ('Center', 'Center'), ('Denied', 'Denied')], max_length=20, null=True)),
                ('questionsConsent', models.BooleanField(default=False)),
                ('aadharAndAbhaConsent', models.BooleanField(default=False)),
                ('bloodConsent', models.BooleanField(default=False)),
                ('familyHead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_head_member', to='database.familyheaddetails')),
                ('familySurveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familysurveyor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='doctorConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('specialization', models.CharField(blank=True, max_length=500, null=True)),
                ('doctorRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('fileUpload', models.FileField(blank=True, upload_to='doctorFolder')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('PatientsConsultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PatientsConsultancy', to='database.familymembers')),
                ('PatientsPathReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PatientsPathReport', to='database.patientspathlab')),
                ('assignedDoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedDoctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
