# Generated by Django 4.2.3 on 2023-09-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_familyheaddetails_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembers',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='patientspathlab',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
