# Generated by Django 4.2.5 on 2023-09-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_familymembers_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyheaddetails',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='familyheaddetails',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='familyheaddetails',
            name='middelName',
        ),
        migrations.AddField(
            model_name='familyheaddetails',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
