# Generated by Django 4.2.5 on 2023-09-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_area_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyheaddetails',
            name='healthPost',
        ),
        migrations.RemoveField(
            model_name='familyheaddetails',
            name='wardName',
        ),
        migrations.AddField(
            model_name='familyheaddetails',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
