# Generated by Django 4.2.5 on 2023-09-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_familyheaddetails_healthpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='demandLetter',
            field=models.ImageField(blank=True, null=True, upload_to='demand letter'),
        ),
    ]
