# Generated by Django 4.2.5 on 2023-09-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_familymembers_demandletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymembers',
            old_name='phone',
            new_name='mobileNo',
        ),
    ]
