# Generated by Django 4.2.5 on 2023-09-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_rename_phone_familymembers_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='memberId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
