# Generated by Django 4.2.5 on 2023-09-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_familymembers_memberid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembers',
            name='aadharCard',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='abhaId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
