# Generated by Django 4.2.5 on 2023-09-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_familymembers_aadharcard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyheaddetails',
            old_name='addressLine1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='familyheaddetails',
            name='addressLine2',
        ),
    ]
