# Generated by Django 4.2.5 on 2023-09-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_phlebotomist'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='cbacScore',
            field=models.IntegerField(default=0),
        ),
    ]
