# Generated by Django 4.2.5 on 2023-09-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_familymembers_cbacscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymembers',
            old_name='partA',
            new_name='Questionnaire',
        ),
        migrations.RemoveField(
            model_name='familymembers',
            name='partB',
        ),
        migrations.RemoveField(
            model_name='familymembers',
            name='partC',
        ),
        migrations.RemoveField(
            model_name='familymembers',
            name='partD',
        ),
        migrations.RemoveField(
            model_name='familymembers',
            name='partE',
        ),
    ]
