# Generated by Django 4.2.5 on 2023-09-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_rename_parta_familymembers_questionnaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='BMI',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='bloodPressure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='pulse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
