# Generated by Django 4.2.5 on 2023-09-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_familymembers_bmi_familymembers_bloodpressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpost',
            name='healthPostName',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='wardName',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
