# Generated by Django 4.2.5 on 2023-09-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_healthpost_healthpostname_alter_ward_wardname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpost',
            name='healthPostName',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
