# Generated by Django 4.2.5 on 2023-10-04 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_alter_area_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phlebotomist',
            name='barcodeNumber',
        ),
        migrations.CreateModel(
            name='TestTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcodeNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('phlebo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phlebo_details', to='database.phlebotomist')),
            ],
        ),
    ]
