# Generated by Django 4.2.5 on 2023-10-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_remove_phlebotomist_barcodenumber_testtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembers',
            name='gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
