# Generated by Django 4.2.6 on 2023-10-13 05:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_alter_familymembers_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amodoctor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Amospecialization', models.CharField(blank=True, max_length=500, null=True)),
                ('AmodoctorRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('AmofileUpload', models.FileField(blank=True, upload_to='doctorFolder')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('AmoPatientsConsultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AmoPatientsConsultancy', to='database.familymembers')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriDoctor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Prispecialization', models.CharField(blank=True, max_length=500, null=True)),
                ('PridoctorRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('fileUpload', models.FileField(blank=True, upload_to='doctorFolder')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('PriPatientsConsultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PriPatientsConsultancy', to='database.familymembers')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Secdoctor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Secspecialization', models.CharField(blank=True, max_length=500, null=True)),
                ('SecdoctorRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('SecfileUpload', models.FileField(blank=True, upload_to='doctorFolder')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('SecPatientsConsultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SecPatientsConsultancy', to='database.familymembers')),
            ],
        ),
        migrations.CreateModel(
            name='TertiaryConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terdoctor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Terspecialization', models.CharField(blank=True, max_length=500, null=True)),
                ('TerdoctorRemarks', models.CharField(blank=True, max_length=500, null=True)),
                ('fileUpload', models.FileField(blank=True, upload_to='doctorFolder')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('TerPatientsConsultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TerPatientsConsultancy', to='database.familymembers')),
            ],
        ),
        migrations.RemoveField(
            model_name='patientspathlab',
            name='TestAssignedAndReport',
        ),
        migrations.RemoveField(
            model_name='patientspathlab',
            name='pathLabPatient',
        ),
        migrations.AddField(
            model_name='patientspathlab',
            name='LabTestReport',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='patientspathlab',
            name='LabTestSuggested',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HB', 'HB'), ('CBC', 'CBC'), ('Platelet Count', 'Platelet Count'), ('PT/INR', 'PT/INR'), ('RBS', 'RBS'), ('S. Total Bilirubin', 'S. Total BilirubinB'), ('S. Direct Bilirubin', 'S. Direct Bilirubin'), ('SGPT/ALT', 'SGPT/ALT'), ('SGOT/AST', 'SGOT/AST'), ('Urea / BUN', 'Urea / BUN'), ('S. Creatinine', 'S. Creatinine'), ('ALP', 'ALP'), ('S. Total Proteins', 'S. Total Proteins'), ('S. Albumin', 'S. Albumin'), ('S. Total Calcium', 'S. Total Calcium'), ('S. Uric Acid', 'S. Uric Acid'), ('S. Cholesterol', 'S. Cholesterol'), ('S. Triglycerides ', 'S. Triglycerides '), ('S. HDL (Direct)', 'S. HDL (Direct)'), ('LDL', 'LDL'), ('VLDL', 'VLDL'), ('Amylase', 'Amylase'), ('T3', 'T3'), ('T4', 'T4'), ('HbA1C', 'HbA1C'), ('S. Electrolytes', 'S. Electrolytes'), ('S. TIBC', 'S. TIBC'), ('LDH', 'LDH'), ('Vit. D', 'Vit. D'), ('Vit. B12', 'Vit. B12'), ('Immunoassays', 'Immunoassays')], default='', max_length=255), default=list, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientspathlab',
            name='PatientSampleTaken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientspathlab',
            name='patientFamilyMember',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientFamilyMember', to='database.familymembers'),
        ),
        migrations.AddField(
            model_name='patientspathlab',
            name='suggested_by_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_by_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientspathlab',
            name='suggested_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='doctorConsultancy',
        ),
        migrations.AddField(
            model_name='tertiaryconsultancy',
            name='TerPatientsPathReport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TerPatientsPathReport', to='database.patientspathlab'),
        ),
        migrations.AddField(
            model_name='tertiaryconsultancy',
            name='TerassignedDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TerassignedDoctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondaryconsultancy',
            name='SecPatientsPathReport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SecPatientsPathReport', to='database.patientspathlab'),
        ),
        migrations.AddField(
            model_name='secondaryconsultancy',
            name='SecSecassignedDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SecassignedDoctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='primaryconsultancy',
            name='PriPatientsPathReport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PriPatientsPathReport', to='database.patientspathlab'),
        ),
        migrations.AddField(
            model_name='primaryconsultancy',
            name='PriassignedDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PriassignedDoctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amoconsultancy',
            name='AmoPatientsPathReport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AmoPatientsPathReport', to='database.patientspathlab'),
        ),
        migrations.AddField(
            model_name='amoconsultancy',
            name='AmoassignedDoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AmoassignedDoctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
