# Generated by Django 4.2.6 on 2023-10-13 05:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_amoconsultancy_primaryconsultancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientspathlab',
            name='LabTestSuggested',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HB', 'HB'), ('CBC', 'CBC'), ('Platelet Count', 'Platelet Count'), ('PT/INR', 'PT/INR'), ('RBS', 'RBS'), ('S. Total Bilirubin', 'S. Total BilirubinB'), ('S. Direct Bilirubin', 'S. Direct Bilirubin'), ('SGPT/ALT', 'SGPT/ALT'), ('SGOT/AST', 'SGOT/AST'), ('Urea / BUN', 'Urea / BUN'), ('S. Creatinine', 'S. Creatinine'), ('ALP', 'ALP'), ('S. Total Proteins', 'S. Total Proteins'), ('S. Albumin', 'S. Albumin'), ('S. Total Calcium', 'S. Total Calcium'), ('S. Uric Acid', 'S. Uric Acid'), ('S. Cholesterol', 'S. Cholesterol'), ('S. Triglycerides ', 'S. Triglycerides '), ('S. HDL (Direct)', 'S. HDL (Direct)'), ('LDL', 'LDL'), ('VLDL', 'VLDL'), ('Amylase', 'Amylase'), ('T3', 'T3'), ('T4', 'T4'), ('HbA1C', 'HbA1C'), ('S. Electrolytes', 'S. Electrolytes'), ('S. TIBC', 'S. TIBC'), ('LDH', 'LDH'), ('Vit. D', 'Vit. D'), ('Vit. B12', 'Vit. B12'), ('Immunoassays', 'Immunoassays')], default=list, max_length=255), size=None),
        ),
    ]
