# Generated by Django 4.2.6 on 2023-10-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_alter_patientspathlab_labtestsuggested'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyheaddetails',
            name='isLabTestAdded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familyheaddetails',
            name='isLabTestReportGenerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familyheaddetails',
            name='isSampleCollected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='isLabTestAdded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='isLabTestReportGenerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='isSampleCollected',
            field=models.BooleanField(default=False),
        ),
    ]
