# Generated by Django 4.2.6 on 2023-10-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_customuser_areamo_amo_customuser_healthpostmo_amo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='healthPost',
            new_name='areahealthPost',
        ),
    ]
