# Generated by Django 4.2.6 on 2023-10-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_rename_healthpost_area_areahealthpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='areahealthPost',
            new_name='healthPost',
        ),
    ]
