# Generated by Django 4.2.6 on 2023-10-16 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_rename_areahealthpost_area_healthpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='dispensary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensaryName', models.CharField(blank=True, max_length=255, null=True)),
                ('disphealthPost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disp_healthpost_name', to='database.healthpost')),
            ],
        ),
    ]
