# Generated by Django 4.2.6 on 2023-10-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0032_rename_healthpostmo_amo_customuser_healthpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='wardMo_Amo',
            new_name='ward',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='areaMo_Amo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='healthPost',
        ),
        migrations.AddField(
            model_name='customuser',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areaAmo_mo_name', to='database.area'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='health_Post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthpostAmo_mo_name', to='database.healthpost'),
        ),
    ]
