# Generated by Django 4.2.6 on 2023-10-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_rename_wardmo_amo_customuser_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientspathlab',
            name='citizenRejectedLabTest',
            field=models.BooleanField(default=False),
        ),
    ]
